### ISSUE TITLE
Question on ```ConstantLengthDataset ```

### ISSUE THREAD

**Issue by lavine-lmu** [huggingface/trl#1000]
I found the ```ConstantLengthDataset ``` quite confused, because according to classs definition in  [```trl/trl/trainer/utils.py```](https://github.com/huggingface/trl/blob/28bdb6a3736b09f8bad7961f16852d052c74ae04/trl/trainer/utils.py#L490), why it returns the same ```input_ids``` and ```lables```. Does the model automatically distinguish between them? If so, how is the automatic distinguishing implemented? Do anyone know what it happens in this classs definition? Thanks!

**Comment by younesbelkada** [comment]
Hi @lavine-lmu 
Thanks for the issue!
In fact since this class is designed only for `xxxForCausalLM` models, the labels are automatically shifted by the model when computing the loss, e.g. here for llama: https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L1058
Therefore we just have to send labels that are identical to input_ids

**Comment by lavine-lmu** [comment]
@younesbelkada Thanks for clarifying this, it is more clear now.

**Comment by younesbelkada** [comment]
Thanks @lavine-lmu , feel free to close the issue!
