### ISSUE TITLE
reward metrics no longer reported to wandb

### ISSUE THREAD

**Issue by winglian** [huggingface/trl#1046]
#954 breaks wandb reporting

**Comment by kashif** [comment]
@winglian let me see if I can add it back

**Comment by mnoukhov** [comment]
As I mentioned on the [discussion in my PR](https://github.com/huggingface/trl/pull/954#issuecomment-1836780709) this issue is unrelated to wandb and is about general logging. Previous logging behaviour was actually previously broken for multi-gpu and my PR moved it to be more in line with regular `Trainer` behaviour: training just logs `loss` and evaluation can log other metrics. 

If we want to log other metrics during training correctly, it's a little non-trivial, but I can implement it if we settle on a specific behaviour

**Comment by kashif** [comment]
yes agree! So lets try to add that previous logging behavior in your PR..  I believe Accelerate has helpers for getting metrics gathered from different workers so that can perhaps be used to get an average over them then...

**Comment by younesbelkada** [comment]
Hi there! Does the issue still persists?

**Comment by lzy37ld** [comment]
Same question here
