### ISSUE TITLE
Correct way to use my dataset to finetune llama2-chat using Qlora

### ISSUE THREAD

**Issue by 990529** [huggingface/trl#1071]
I use PEFTTrainer to make the finetune for a based_text q&a task.
![1](https://github.com/huggingface/trl/assets/98394002/f94914b3-8ea8-4de9-8e4b-19be01e2221b)
For the dataset, it appears to be a folder version with 3 files, The pictures show how it look like in colab and how I get it.
![2](https://github.com/huggingface/trl/assets/98394002/13a8d595-e7c5-4886-a0d9-37f1707595f2)
![3](https://github.com/huggingface/trl/assets/98394002/52bd1292-e265-4d30-9035-8e5ba9ccea9b)
My text looks like this format
![4](https://github.com/huggingface/trl/assets/98394002/7fad5dd0-98f0-4a91-94bb-9deb3360afbb)
I want to know why the answer of finetuned_model looks like this?
![image](https://github.com/huggingface/trl/assets/98394002/55048cc1-3424-402a-861d-b718e8c0c473)
By the way, if only text is needed during finetune, how does the machine know which is my input and which is my target output?
Many Thanks!!!!

**Comment by younesbelkada** [comment]
Hi @990529 
Thanks for the issue, can you elaborate on how do you prompt your model? It also looks you're not adding EOS tokens in your dataset making your model generate infinitly. You can also set a custom stopping criteria, in your case it could be a `\n` so that as long as your model generates `\n` it will stop generating new tokens.
