### ISSUE TITLE
How to prepare multi-turn dialogue dataset for dpo?

### ISSUE THREAD

**Issue by chloefresh** [huggingface/trl#1115]
the single-turn dialogue dataset is like:
dpo_dataset_dict = {
    "prompt": [
        "hello",
        "how are you",
        "What is your name?",
        "What is your name?",
        "Which is the best programming language?",
        "Which is the best programming language?",
        "Which is the best programming language?",
    ],
    "chosen": [
        "hi nice to meet you",
        "I am fine",
        "My name is Mary",
        "My name is Mary",
        "Python",
        "Python",
        "Java",
    ],
    "rejected": [
        "leave me alone",
        "I am not fine",
        "Whats it to you?",
        "I dont have a name",
        "Javascript",
        "C++",
        "C++",
    ],
}

So, how to prepare a multi-turn dialogue dataset? Can you provide an example? Thank you!

**Comment by lvwerra** [comment]
Not sure this is currently support @kashif?

**Comment by dmazzaccara** [comment]
Hi @kashif, any news on this? 

I have multi-turn conversational dataset, with chosen and rejected answers at each turn. I divide the conversations at each turn and update conversations only with chosen answers (formatted for Llama-2-chat template). The dataset is like this (one conversation with two turns): 

dpo_dataset_dict = {
"prompt": [
"<s>[INST] <<SYS>> You are an assistant <</SYS>> Tell me three words [/INST]",
"<s>[INST] <<SYS>> You are an assistant <</SYS>> Tell me three words [/INST] Hugging, Face, hello </s><s>[INST] Tell me the first of the previous words [/INST] ",
],
"chosen": [
"Hugging, Face, hello",
"Hugging",
],
"rejected": [
"Hugging, Face, hello, review",
"Face",
],
}

The trained adapter ([DPO llama2-chat](https://huggingface.co/blog/dpo-trl)) generates too much text for turn and for both "players", probably due to a tokenization problem of the training inputs. Is it related to this issue #884? Any suggestions on how to deal with this?

**Comment by dmazzaccara** [comment]
Hi, any news on this?

I have multi-turn conversational dataset, with chosen and rejected answers at each turn. I divide the conversations at each turn and update conversations only with chosen answers (formatted for Llama-2-chat template). The dataset is like this (one conversation with two turns):

dpo_dataset_dict = {
"prompt": [
"[INST] <> You are an assistant <> Tell me three words [/INST]",
"[INST] <> You are an assistant <> Tell me three words [/INST] Hugging, Face, hello [INST] Tell me the first of the previous words [/INST] ",
],
"chosen": [
"Hugging, Face, hello",
"Hugging",
],
"rejected": [
"Hugging, Face, hello, review",
"Face",
],
}

The trained adapter ([DPO llama2-chat](https://huggingface.co/blog/dpo-trl)) generates too much text for turn and for both "players", probably due to a tokenization problem of the training inputs. Is it related to this issue https://github.com/huggingface/trl/issues/884? Any suggestions on how to deal with this?

**Comment by dmazzaccara** [comment]
Hi @kashif, any update on this?

I have multi-turn conversations, that I divided in turns and updated the dialogue history with only chosen answers (formatted for Llama-2-chat). The resulting dataset have this form (example of one conversation with 2 turns): 

```
dpo_dataset_dict = {
"prompt": [
"<s>[INST] <<SYS>> You are an assistant <</SYS>> Tell me three words [/INST]",
"<s>[INST] <<SYS>> You are an assistant <</SYS>> Tell me three words [/INST] Hugging, Face, Hello </s><s> 
[INST] Tell me the first of your words [/INST]",
],
"chosen": [
"Hugging, Face, Hello",
"Hugging",
],
"rejected": [
"Hugging, Face, Hello, review",
"Face",
]
}
```

I have trained a [llama adapter with DPO](https://huggingface.co/blog/dpo-trl), that generates too much text and for both "players". I suppose this is due to a tokenization problem of the training inputs. Is it related to the issue #884? Any suggestions on this?

**Comment by Ricardokevins** [comment]
> Not sure this is currently support @kashif?

I still have question here

Like Anthropic/hh-rlhf is a multi-turn dataset, how to get it to a DPO dataset

**Comment by kashif** [comment]
so typically the last response is used to create positive / neg. binarized pref. data... if there are multiple ranked responses, one heuristic is to take the best response as the positive and then randomly select the other responses to be the unprefered ones. In this way one can create a DPO dataset

**Comment by ezosa** [comment]
> so typically the last response is used to create positive / neg. binarized pref. data... if there are multiple ranked responses, one heuristic is to take the best response as the positive and then randomly select the other responses to be the unprefered ones. In this way one can create a DPO dataset

I am not sure I understand the idea here. To take an example, the [HelpSteer2](https://huggingface.co/datasets/nvidia/HelpSteer2) dataset has a multi-turn conversation as prompt (separated by _<extra_id_1>Assistant_ and _<extra_id_1>User_) and there are two responses to the last user turn with their helpfulness scores. We can use the helpfulness score to select the chosen and rejected response. However, it seems that TRL does not accept a multi-turn conversation as prompt. How should we format the DPO dataset in this case?
