### ISSUE TITLE
DPOTrainer.tokenize_row is not hashable

### ISSUE THREAD

**Issue by normster** [huggingface/trl#1252]
`DPOTrainer.tokenize_row` is not hashable, so the `datasets` library assigns the transformed dataset a "random" fingerprint. This fingerprint relies on the `random` library, but since the random seed is often fixed in training configs this always yields the same fingerprint across different runs even when the underlying dataset is completely different: https://github.com/huggingface/datasets/issues/6604.

The immediate fix should be to change the fingerprinting logic in `datasets` to use a library like `uuid` to guarantee different fingerprints each run. But even after this is fixed, `tokenize_row` not being hashable will trigger re-processing every run, which is slow and wasteful. Is there any way to make it hashable so we can leverage caching?

**Comment by lvwerra** [comment]
Maybe a quick solution could be to change the processing function that's passed to `.map` to a standalone function rather than a class method. cc @kashif

**Comment by norabelrose** [comment]
Bumping this so it's not stale anymore; still a problem

**Comment by younesbelkada** [comment]
cc @kashif what do you think? 🙏

**Comment by thusinh1969** [comment]
Really wasting time too much. Please fix. Takes hours to starf.

Steve

**Comment by thusinh1969** [comment]
BTW. Unsloth run Ok without this problem but single GPU only.

**Comment by Ghubertang** [comment]
I really need this to be fixed. Please. Waiting too long to start a training.

**Comment by thusinh1969** [comment]
Same here...please fix.

**Comment by Shiguang-Guo** [comment]
same problem , and it takes me up to half an hour to process data (whether it is ten thousand or one hundred). I am a little curious about what it is waiting for. Is this the same issue caused by not hashable?

Map (num_proc=32): 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████| 152583/152583 [32:57<00:00, 77.18 examples/s]
Map (num_proc=32): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 997/997 [30:33<00:00,  1.84s/ examples]
Map (num_proc=32): 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 100/100 [30:08<00:00, 18.08s/ examples]

**Comment by kashif** [comment]
refresh! on it currently
