### ISSUE TITLE
IPO Correction

### ISSUE THREAD

**Issue by kangqi-ni** [huggingface/trl#1294]
I heard that trl had an incorrect implementation for IPO and they have corrected that, so which version of trl should I use for the correct implementation of IPO?

**Comment by younesbelkada** [comment]
hi @kangqi-ni 
Indeed! for that please use the main branch of TRL for now !

**Comment by kmn1024** [comment]
Is this the fix? https://github.com/huggingface/trl/pull/1265/

Also, I'm a bit confused by beta selection. I saw this blogpost: https://huggingface.co/blog/pref-tuning#zephyr-7b-beta-sft, and it seems to suggest using a relatively large beta for IPO after the fix, which strangely means we want less separation between chosen vs rejected pairs?

**Comment by lewtun** [comment]
Hi @kmn1024 yes that PR is the fix (we should add a pointer to it in the blog post, so will add it there). 

Regarding the values for beta (or tau in the IPO paper), we find that in general the best choice is model/dataset dependent. The main message from the figures of the IPO paper is that beta acts as a regulariser, where small values equate to mostly picking the chosen response (i.e. "greedy policy"). 

From discussions we've had with the IPO authors, the general expectation is that you should see a "hump" in performance, where very small values of beta give poor performance (greedy, overfitting), intermediate values give good perf and large values give poor perf (underfitting). However, we have not been able to accurately produce this behaviour in MT Bench and it is possible the issue lies with the random fluctuations associated with this benchmark.

cc @edbeeching @kashif 

![Screenshot 2024-01-31 at 08 48 49](https://github.com/huggingface/trl/assets/26859204/64fe3615-1493-474a-8e09-01f64b40dc8e)

**Comment by lewtun** [comment]
Blog post pointer here: https://github.com/huggingface/blog/pull/1785
