### ISSUE TITLE
Token-level reward for PPOTrainer

### ISSUE THREAD

**Issue by piyush-J** [huggingface/trl#1395]
Hi, 

Thank you for this amazing library! 

I wanted to use PPOTrainer for a task that provides token-level rewards. If I understand correctly, the reward we provide in the step() function is a scalar reward corresponding to the predicted sequence of output tokens. However, instead of the scalar reward, is there any way I can use a reward vector where there is a reward value corresponding to every output token (i.e., `len(reward_vector) == len(pred_output_tokens)`)? If the PPOTrainer does not support this, is there any alternative hack/trick I can use?

Thank you in advance!

**Comment by AppaYiipYiip** [comment]
Hi there!

I noticed you're one of the co-authors of the recent RLSF paper ("RLSF: Fine-tuning LLMs via Symbolic Feedback") - fantastic work!

I'm actually trying to implement the RLSF method described in your paper, and I see that you faced the exact same challenge you're asking about here. From the paper, I understand that you successfully modified the TRL library to support token-level reward vectors instead of scalar rewards, as mentioned in Appendix D:

_"However, TRL only allows for scalar reward signals during the RL fine-tuning process. We modify the library to support reward vector (dense) signals, allowing fine-grained feedback at the token level."_

Would you be willing to share the modified TRL code or the specific changes you made to enable token-level rewards? This would be incredibly helpful for reproducibility and for others trying to implement similar symbolic feedback approaches.

I understand this might involve some effort to clean up and share the code, but it would be a valuable contribution to the community, especially given the promising results you achieved with RLSF.

Thank you for your amazing work on this research, and I hope you might consider sharing the implementation!

Best regards,
Marouane
