### ISSUE TITLE
How many GPUs needed?

### ISSUE THREAD

**Issue by Wallace-222** [huggingface/trl#693]
Hello authors, thanks for your work. I want to know how many and what kinds of gpus do I needed to run the following experiment:

Supervised fine-tuning of the base llama-v2-7b model to create llama-v2-7b-se:
accelerate launch examples/stack_llama_2/scripts/sft_llama2.py --output_dir="sft"

**Comment by lllcc** [comment]
and how many gpus for dpo_llama2.py with llama-2-7b

**Comment by lvwerra** [comment]
We ran our experiments on A100 (80GB) but you might be able to use smaller GPUs. Note that we rely only on Data Parallel: so you can either use just 1 GPU or more the difference will just be training speed.

**Comment by raihan0824** [comment]
> We ran our experiments on A100 (80GB) but you might be able to use smaller GPUs. Note that we rely only on Data Parallel: so you can either use just 1 GPU or more the difference will just be training speed.

If I don't use 4bit quantization, the model doesn't fit on my A100 40GB GPU, and when I use accelerate for distributed training, as you said, the difference seems to be only the training speed, because it still OOM. Is it somehow possible to fit the model into multiple GPUs even though it will slows the training? The goal is to prevent the OOM. I have 4 A100 GPU.

**Comment by lvwerra** [comment]
With the 7B model I believe everything should fit into 40GB GPU memory. What settings are you running?
