### ISSUE TITLE
DPO trainer: why switch off dropout in both policy and ref models

### ISSUE THREAD

**Issue by haorannlp** [huggingface/trl#744]
See code at [Here](https://github.com/huggingface/trl/blob/453c4eca14007e2e13a2d75863683199de2c0861/trl/trainer/dpo_trainer.py#L168)  

> https://github.com/huggingface/trl/blob/453c4eca14007e2e13a2d75863683199de2c0861/trl/trainer/dpo_trainer.py#L168-L171

If both dropouts are switched off, and ref and policy models are initialzied the same, the dpo loss should be `-logsimoid(0)`, there should be no gradient for model params then..

**Comment by kashif** [comment]
so the original code base also disabled dropout for both main and reference model, but you are referring to the issue of symmetry-breaking? my intuition was that since these models are probabilistic models the samples should have some variance in them to be able to get a signal with respect to the loss... and perhaps after the first step of sgd the models will not be the same...

**Comment by kazemnejad** [comment]
why don't you have disable dropout in PPOTrainer? Any specific reason?

**Comment by erfanMhi** [comment]
@kazemnejad This is the reason they mention in their paper:
"**We disable the dropout layers during training, similar to the settings in Ziegler et al; Huang et al. This is important for PPO training, especially because with dropout activated, the log probabilities of tokens will not be reproducible, making calculating the KL penalty unreliable while also causing the ratios of the PPO to be not 1s during the first epoch, causing PPO optimization problems. For consistency, we also disable dropout for SFT and RM training**."

Hope it helps. 

Paper: https://arxiv.org/html/2403.17031v1
