### ISSUE TITLE
Best way to get custom GPT2 and tokenizer to work with ppo_trainer?

### ISSUE THREAD

**Issue by h-clickshift** [huggingface/trl#845]
I have trained my sft model with [nanoGPT](https://github.com/karpathy/nanoGPT/blob/master/model.py) in torch(without transformer), also I defined a custom tokenizer without transformer libs.
Now I am tuning  trl(ppo) to reinforce my sft model, and I get
![6cf11a3b-9dce-447e-9a12-397b05460872](https://github.com/huggingface/trl/assets/117718271/69a5e01d-f28e-47b4-a864-965ac90efa37)
any ideas?

**Comment by 3Spiders** [comment]
i have similar issue.

**Comment by lvwerra** [comment]
If you want to use a custom model you need to register it in `transformers` since we rely heavily of the model and tokenizer classes in TRL. Here's a guide for the model: https://huggingface.co/docs/transformers/custom_models. For the tokenizer you can probably just subclass it as long as you make sure the class methods are consistent.

**Comment by lvwerra** [comment]
Closing for now, feel free to reopen if there's an update.
