### ISSUE TITLE
What are the purposes of `label_pad_token_id` and `padding_value` in `DPOTrainer`?

### ISSUE THREAD

**Issue by nathan-az** [huggingface/trl#909]
Why is it required to set these two arguments? My first guess was that `padding_value` would be the pad token? But it's not clear to me why these are specified, and why they are separate from the tokenizer's values, `tokenizer.pad_token` and `tokenizer.pad_token_id`, and how these two interact, or if they should be set to agree with each other.

**Comment by lvwerra** [comment]
cc @kashif

**Comment by kashif** [comment]
@nathan-az so I have refactored the trainer and removed the need for `padding_value` which is essentially the `tokenizer.pad_token_id` used to pad the input_ids so that sequences have the same shape in a batch... 

g'day nathan! I noticed that we were using the `padding_value` to also pad the attention mask which is either 0 and 1 and thus now i explicitly set the pad values for the attention mask to 0 and take the`padding_value` from the `tokenizer.pad_token_id` and use it appropriately. The refactoring is here:

https://github.com/huggingface/trl/pull/885

**Comment by lvwerra** [comment]
Closing this for now, feel free to reopen should you have further questions!
