### ISSUE TITLE
Tensor Parallel and Pipeline parallel

### ISSUE THREAD

**Issue by yuanenming** [huggingface/trl#962]
Thanks for sharing the awesome repo.

Recently, I am using TRL to train LLM (~100B) models using the DPO algorithm. It works well when using Deepspeed Zero-3 on 16 8xA100 Nodes with full-parameter finetune. When I want to extand the sequence length from 4k to even longer, it will cause OOM error. I believe it is because the activation is to large and dominate the GPU memory when sequence length is larger.

So I want to know if it possible to use TP and PP to further improve the sequence length. I saw there is a doc page about Megatron-LM in accelerate https://huggingface.co/docs/accelerate/usage_guides/megatron_lm . But it only works on GPT, BERT and T5 and it does not support flash attention 2.

Do you have any suggestions on my scenario? I would very glad to contribute an MR.

**Comment by lvwerra** [comment]
Hi @yuanenming, glad to hear that TRL scales to 100B parameters! I'd be glad to hear more about that use-case since it's likely one of the largest models ever trained with TRL! 

Have you tried combining DS Zero-3 with PEFT? That could be a way to improve memory consumption. In most experiments we ran, we could achieve similar results with just LoRA. I understand from your description that you are already using FlashAttention2? I am also tagging @pacman100 who is more knowledgeable on DeepSpeed related issues. 

Indeed Megatron is not an option since it's not model agnostic and we have never tested if the `accelerate` integration works with TRL even with the supported models.

**Comment by noamgat** [comment]
Have you made any progress on this? I am also having trouble using max_seq_length=8192. It seems that no matter what the config is, each gpu will have at least one minibatch exclusively on it, while I am looking to split one minibatch between several GPUs due to the activation buffers.

**Comment by kwen2501** [comment]
Hi, a new pipeline parallel solution was recently added in pytorch if you are interested: [torch.distributed.pipelining](https://github.com/pytorch/pytorch/tree/main/torch/distributed/pipelining)

It is a **model agnostic** solution. You can pipeline a GPT2 model with a simple spec:
```
# Split specification per your need
decoders_per_rank = gpt2.config.n_layer // args.world_size
split_spec = {
    f'transformer.h.{i * decoders_per_rank}': SplitPoint.BEGINNING
    for i in range(1, args.world_size)
}

# Create pipeline representation
pipe = pipeline(
    gpt2,
    mb_args=(),
    mb_kwargs=mb_inputs,
    split_spec=split_spec,
)
```
It is planned to release in pytorch 2.4, but it is available now through pytorch nightly.

About 20 HF examples are available here:
https://github.com/pytorch/PiPPy/tree/main/examples/huggingface
(Most of them are yet to be migrated from the pippy APIs to the `torch.distributed.pipelining` APIs. But they are rather similar.)

**Comment by UCC-team** [comment]
Hello, could you please tell me how you use TRL to train LLM (~100B) models? I have encountered the same issue when I was training a 72B SFT model. My sequence length is longer than 8192.

**Comment by YangZeyu95** [comment]
same issue

**Comment by JaumePrats** [comment]
Any news on this matter?
