### ISSUE TITLE
Issue when using the Mistral tokenizer with DataCollatorForCompletionOnlyLM

### ISSUE THREAD

**Issue by BayesRulez** [huggingface/trl#980]
Hi,

First off - thanks to everyone who worked to get the Mistral models into HF so quickly.  They're a joy to use and the hard work is appreciated.

I've isolated what I think is a problem with the Mistral tokenizer.  It crops up when using the `DataCollatorForCompletionOnlyLM`.

Here is the minimal code to reproduce the issue.

```
from transformers import AutoTokenizer
from trl import DataCollatorForCompletionOnlyLM

base_model_id = "mistralai/Mistral-7B-Instruct-v0.1"
tokenizer = AutoTokenizer.from_pretrained(base_model_id)
prompt = "[INST]What is the capital of the United Kingdom?[/INST]London</s>"
input_ids = tokenizer(prompt)["input_ids"]
collator = DataCollatorForCompletionOnlyLM("[/INST]", tokenizer=tokenizer)
collator([input_ids])
```

Running the above will cause `trl` to raise a warning: 

```UserWarning: Could not find response key `[/INST]` in the following instance: <s> [INST]What is the capital of the United  Kingdom?[/INST]London</s> This instance will be ignored in loss calculation. Note, if this happens often, consider increasing the `max_seq_length`.```

And the `labels` tensor that is returned contains only -100 values.

However, if you call `collator([input_ids])` a _second_ time the warning will not be raised.

A further observation: the tokenizer adds the `<s>` token to the start of any input, but does not add the `<\s>` to the end.  (Hence why I add it manually in the example above.)  Not sure if this is intentional, or not.

**Comment by vikram71198** [comment]
Hi, this really isn't a bug with the tokenizer itself, more so an effect of how the tokenizer tokenizes differently based on context.

Replace your code with the snippet below and you should see the problem you currently face evaporate:

```
from transformers import AutoTokenizer
from trl import DataCollatorForCompletionOnlyLM

base_model_id = "mistralai/Mistral-7B-Instruct-v0.1"
tokenizer = AutoTokenizer.from_pretrained(base_model_id)
prompt = "[INST]What is the capital of the United Kingdom?[/INST]London</s>"
input_ids = tokenizer(prompt)["input_ids"]
collator = DataCollatorForCompletionOnlyLM(tokenizer.encode("\n[/INST]", add_special_tokens = False)[2:], tokenizer=tokenizer)
collator([input_ids])
```
HuggingFace has explained this workaround [here](https://huggingface.co/docs/trl/main/en/sft_trainer#using-tokenids-directly-for-responsetemplate).

Essentially, you include the `"\n"` as a substitute for any context that could precede the `response_template`. And use the `token_ids` instead of the string itself to isolate the completion.

Everything from the start of the prompt to the end of the `response_template` should be -100 (`ignore_index`) and only your completion tokens will be retained. All the -100 tokens are then ignored by `CrossEntropyLoss`, which is the desired effect.

**Comment by BayesRulez** [comment]
Hi @vikram71198,

Thanks for taking the time to read and respond.  I've just switched to Mistral and haven't come across the context-sensitive tokenizer before.

I can confirm that your code works, so a big thank you for drawing my attention to the work-around :-)

Will
