### ISSUE TITLE
Dataloader always drop last batch in PPO

### ISSUE THREAD

**Issue by allanj** [huggingface/trl#998]
https://github.com/huggingface/trl/blob/e23a541af93adf9d38665e8e75a2488b4d9e78d9/trl/trainer/ppo_trainer.py#L387-L393

Is this expected?

I believe we should have an option for that?

**Comment by younesbelkada** [comment]
Hi @allanj  Yes this is expected to avoid some issues we had in the past, please check out this PR: https://github.com/huggingface/trl/pull/154 for more details

**Comment by allanj** [comment]
Thanks. I just checked. Is it better to let the developer pass in the data loader in that case? XD. In my experiments, I prefer to go through all the batches. 

Not sure if there are more elegant ways for me to do that

**Comment by younesbelkada** [comment]
Thanks! 
I think in all cases you need to drop the last batch to avoid issues such as: https://github.com/huggingface/trl/issues/148 , this is because of the way `PPOTrainer` has been designed :/ 
To make sure you pass all your batches perhaps you can just have a dataset that has a multiple of `batch_size` examples and you add a single dummy instance to it at the end to that it gets dropped.
